name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Formatting
      run: cargo fmt --check
    - name: Install wasm32 toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Linting
      run: cargo clippy --target wasm32-unknown-unknown
    - name: Build
      run: sh build.sh
